name: Main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN }}

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2  # Fetch last 2 commits to compare changes
    - name: Get changed files
      id: changed-files
      run: |
        echo "FILES=$(git diff --name-only HEAD~1 HEAD | tr '\n' ' ')" >> $GITHUB_ENV
    - name: Install and run Spectral CI
      uses: checkpointsw/spectral-github-action@v3
      with:
        spectral-dsn: ${{ env.SPECTRAL_DSN }}
        spectral-args: scan --fail-on-error --validate --engines secrets,iac,oss --include-tags base,audit3,iac ${{ env.FILES }}
